### ISSUE TITLE
insertAfter, addCatch not working with constructor and static method that throws Exception

### ISSUE THREAD

**Issue by dkarv** [jboss-javassist/javassist#149]
I noticed an unexpected behavior in Javassist. I instrument methods with the insertBefore, insertAfter and addCatch of CtBehavior:
```
method.insertBefore("System.out.println(\"before " + method.getName() + "\");");
method.insertAfter("System.out.println(\"after " + method.getName() + "\");", true);
CtClass etype = ClassPool.getDefault().get("java.lang.Exception");
method.addCatch("{ System.out.println(\"catch " + method.getName() + "\"); throw $e; }", etype);
```

Running it on the following class:
```
public class Example {
    public Example() {
        this(Example.exception());
    }
    public Example(int i) {}
    public static int exception() {
        throw new IllegalArgumentException("Error");
    }
    public static void main(String[] args) {
        new Example();
    }
}
``` 
# Output:
```
before main
before Example
before exception
after exception
catch exception
after main
catch main
```
# Expected output (difference marked with `>`):
```
before main
before Example
before exception
after exception
catch exception
> after Example
> catch Example
after main
catch main
```
So somehow the insertAfter and addCatch methods do not work on the constructor in the given code. I noticed this in some real-world examples.
# Environment
I'm using Java 1.8.0_131 and Javassist 3.22.0-CR2, but it happens on older versions, too.
You can find a [minimal example here](https://github.com/dkarv/javassist-bugreport).
Is this a known issue? Any workarounds?

**Comment by nickl-** [comment]
could be related to #155

**Comment by nickl-** [comment]
Can reproduce, thank you for supplying a test case.

However what  you fail to mention is that the exception is not handled, so the actual results are:

```
before main
before Example
before exception
after exception
catch exception
after main
catch main
Exception in thread "main" java.lang.IllegalArgumentException: Error
	at example.Example.exception(Example.java:13)
	at example.Example.<init>(Example.java:6)
	at example.Example.main(Example.java:17)
```

While attempting to prove that this only happens when passing to constructor the result of a static method which throws exception I managed to produce the "expected results" when passing to an instance method the result of an instance method which throws exception.

```java
public class Example {

    public Example() {
        this.exampleMeth(this.exception());
    }

    public void exampleMeth(int i) {
    }

    public int exception() {
        throw new IllegalArgumentException("Error");
    }

    public static void main(String[] args) {
        new Example();
    }
}
```

Results:
```
before main
before Example
before exception
after exception
catch exception
after Example
catch Example
after main
catch main
Exception in thread "main" java.lang.IllegalArgumentException: Error
	at example.Example.exception(Example.java:13)
	at example.Example.<init>(Example.java:6)
	at example.Example.main(Example.java:17)
```

Taking one step back by passing the result of a static method that throws exception to an instance method, it produced the same "expected results".

```java
public class Example {

    public Example() {
        this.exampleMeth(Example.exception());
    }

    public void exampleMeth(int i) {
    }

    public static int exception() {
        throw new IllegalArgumentException("Error");
    }

    public static void main(String[] args) {
        new Example();
    }
}
```

But then it dawned on me, perhaps we are getting the correct results after all. Lets look closer at what is happening here.

If we step through the last two examples we get the following:

1. `before main` calls `new Example()`
1. `before Example` calls `exception()` (to pass return to `exampleMeth`)
1. `before exception` throws exception
1. `after exception` catches exception
1. `catch exception` throws exception (rolling back `exampleMeth` doesn't get called nothing returned by exception.)
1. `after Example` catch exception
1. `catch Example` throws exception
1. `after main` catch exception
1. `catch main` throw exception

So why does this differ from the original example, lets have a look

1. `before main` calls `new Example()`
1. `before Example` calls `exception()` (to pass return to `this(int)`)
1. `before exception` throws exception
1. `after exception` catches exception
1. `catch exception` throws exception (rolling back constructor doesn't get called no Example instance)
1. `after main` catch exception
1. `catch main` throw exception

The `after Example` and `catch Example` calls are only possible after `Example.this` was established. Since the call to the constructor was aborted we never managed to create a new `Example` instance so it rolls back to the main method, before calls could be made to prompt `after Example` and `catch Example`.

if you agree:

**Suggest close issue
Reason: Works as expected**

**Comment by dkarv** [comment]
Thanks for your response.
I think I understand the problem and yes it might indeed be the right behavior, although not really intuitive. I would at least expect it to print `catch Example`, because the constructor clearly throws an exception I want to catch.
I will close the issue and look for a workaround. For my application I have to make sure to receive `before` and `after` for every method/constructor.

**Comment by nickl-** [comment]
@dkarv the fact that we manage to print the before in the constructor is the crazy/confusing part since that will not compile if we attempted to write it with source code.

The first line of a constructor is special, we do not have `this` yet there is no instance if the 1st line doesn't succeed, I expect you will see similar results if `super` throws an exception for example, unless the 1st line succeeds the constructor chain is aborted which prevents anything being caught.

You also cannot compile something like:

```java
public class Abc {
     public Abc() {
         try {
             super(); // Error: Constructor call must be the first statement in a constructor
         } catch (Exception e) { }
     }
}
``` 

So even though the direct byte code manipulation manages to accomplish this it does not work exactly as you might expect. If you imagine that it looks more like this:

```java
public class Abc {
     public Abc() {
         super(); // First line of constructor is special/static, this not available
         try {
              // this available, we have new instance of Abc
         } catch (Exception e) { }
     }
}
``` 

It might make more sense.
