### ISSUE TITLE
Javassist Android Gradle Plugin setSuperclass no-op

### ISSUE THREAD

**Issue by AlexShafir** [jboss-javassist/javassist#151]
Hi Shigeru, 

I found inexplicable behaviour of Javassist setSuperclass.

I created Android Gradle Plugin which uses Transform API.

Via Transform API, I obtain `.class` files which I instrument with the help of Javassist.

I have annotation `@MultipleExtends(Class a, Class b)`, which annotates other classes like

    @MultipleExtends({DrawerFragment.class, MyLocationEnabledFragment.class})
    public class AwesomeFragment extends Fragment {
        // any other code
    }

I copy class `a` and `b`, append "_magic" word to their names, save to original folder.

Then I make class `b` extend from class `a`, class with annotation extend from class `b`.

All these `.class` manipulations are done via Javassist.

Thing is, it's not working despite that in APK I see new classes and edits and in runtime when I log superclass of class with annotation new name appears!

What I may possibly do wrong?

Source code is [here][1]

  [1]: https://github.com/AlexShafir/MultipleExtends

**Comment by nickl-** [comment]
Correction [branch bytecode-inheritance](https://github.com/AlexShafir/MultipleExtends/tree/bytecode-inheritance)

@AlexShafir did u manage to find join?

**Comment by AlexShafir** [comment]
Hi Nick,

What does "join" mean?

What am I supposed to find? :)

11 нояб. 2017 г. 10:58 PM пользователь "Nick Lombard" <
notifications@github.com> написал:

**Comment by nickl-** [comment]
> What does "join" mean?
> What am I supposed to find? :)

@AlexShafir Almost had me there for a second, because the post does not say join anymore. It was a typo which I fixed immediately after posting but I see you responded via email. Obviously the edited post correction didn't fix the emailed notification already sent. My apologies for the confusion, I will attempt to explain with more details this time. If you visit the thread at #151 everything should make more sense as well.

The corrected question reads: did you manage to find joy? (not join) In other words did you solve the problem, did you have success or are you happy now? 

The reason I am asking is because I noticed that you have made several commits to your [bytecode-inheritance](/AlexShafir/MultipleExtends/tree/bytecode-inheritance) project after you created this issue (#151). These include some extensive documentation changes which makes it appear that the project has reached some level of completion. I may be mistaken...

If **"javassist setSuperclass no-op"** is not a problem for you anymore or if you managed to find a work around will you please let us know. You will be saving time, otherwise needlessly spent investigating an issue, which has already been resolved.

**Comment by AlexShafir** [comment]
Hi Nick,

Thanks for reply & attention to my efforts!

My task was to combine classes that extend from same classes and only
override methods of their superclass i.e. react to lifecycle events, for
example AwesomeFragment and MyLocationEnabledFragment.
Their actions may have side-effects, but their results do not intersect.
Thus we can call their methods in any order.

However, with release of Google's Architecture Components I realized that I
can simply create observer pattern and thus delegate callbacks of Fragment
to it's "subscribers".

I think this is the right way.


27 нояб. 2017 г. 9:57 AM пользователь "Nick Lombard" <
notifications@github.com> написал:

What does "join" mean?
What am I supposed to find? :)

@AlexShafir <https://github.com/alexshafir> Almost had me there for a
second, because the post does not say join anymore. It was a typo which I
fixed immediately after posting but I see you responded via email.
Obviously the edited post correction didn't fix the emailed notification
already sent. My apologies for the confusion, I will attempt to explain
with more details this time. If you visit the thread at #151
<https://github.com/jboss-javassist/javassist/issues/151> everything should
make more sense as well.

The corrected question reads: did you manage to find joy? (not join) In
other words did you solve the problem, did you have success or are you
happy now?

The reason I am asking is because I noticed that you have made several
commits to your bytecode-inheritance
<http:///AlexShafir/MultipleExtends/tree/bytecode-inheritance> project
after you created this issue (#151
<https://github.com/jboss-javassist/javassist/issues/151>). These include
some extensive documentation changes which makes it appear that the project
has reached some level of completion. I may be mistaken...

If *"javassist setSuperclass no-op"* is not a problem for you anymore or if
you managed to find a work around will you please let us know. You will be
saving time, otherwise needlessly spent investigating an issue, which has
already been resolved.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jboss-javassist/javassist/issues/151#issuecomment-347104353>,
or mute the thread

**Comment by nickl-** [comment]
> However, with release of Google's Architecture Components I realized that I
can simply create observer pattern and thus delegate callbacks of Fragment
to it's "subscribers".
>
> I think this is the right way.

Makes sense.

**Suggest close issue
Reason: User found work around.**
