### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by emanoelbarreiros** [jboss-javassist/javassist#214]
When using version 3.15.0-GA, I get the following warning at runtime:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/Users/emanoel/.m2/repository/org/javassist/javassist/3.15.0-GA/javassist-3.15.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I am just doing what the "gods" of runtime asked me.

**Comment by nickl-** [comment]
That is so nice of you... did you tell your mommy too?

**Comment by emanoelbarreiros** [comment]
Actually I told yours last night... Do you really have to be so rude?

I dia a search on the issues on the repository and found none mentioning this problem. Maybe you already knew about it, maybe not, so I tried to help. Anyway, shut that attitude in your fucking ass, be a real developer (and a man) and appreciate the free help.

Cheers.

**Comment by nickl-** [comment]
Wow and she taught you nice manners too.

Do you understand what that issue is about?
Do you even know what this project does? These questions are rhetoric, of course you don't.

How exactly are you helping? This question you should seriously go think about.

So everything is working as expected, there's no problems nothing is broken but there's this pesky message instructing you to go tell so and so that even though their stuff works like a charm and didn't cost you a dime they have to stop everything and take note of this.

No where in between taking instruction from a log message to finding this issue tracker and submitting the ticket did you once stop to think.

I wonder what this warning is about, should I really go and tell them or do you think they know already?
Oh and perhaps I should check and see what this project actually does first before I embarrass myself.

For now focus on helping yourself first only then will you be of any use to others. Look for something to learn from every encounter. Find out what is important to you in this life and choose your battles accordingly. Life is too short to take everything so seriously...

Close this issue... no body here wants to hear about it.

**Comment by emanoelbarreiros** [comment]
I'll leave it open. Maybe you find some time to fix it when things actually break.

**Comment by chibash** [comment]
Hi Emanoel,

Fixing a bug reported in this sort of style is very difficult.  Your bug report does not mention which version of the JVM is used or which code you ran when producing the bug.  You might not be able to post your proprietary code here but imagine how difficult it is to guess the reason of the bug without the program producing that bug!

[For example, see this.](https://medium.com/@Haje/how-to-write-the-perfect-bug-report-6430f5a45cd)

As for your bug, I suppose your Javassist is too old to run on Java 9 or newer.  Use the latest one.
Since Java 9 threw the backward compatibility away, the old versions never run on Java 9 or 10.

**Comment by AlanBateman** [comment]
The warning means there is code in javassist-3.15.0-GA.jar that is hacking into ClassLoader.defineClass, probably to invoke it from the wrong context (ClassLoader.defineClass is a protected member, not a public member). JDK 9, JDK 10, and JDK 11 emit this warning to make maintainers aware that they have code that will break once the java.base module is fully encapsulated. Running with  `--illegal-access=deny` is a useful way to test this out in advance of this change.

As regards this specific bug report then running with `--illegal-access=debug` will emit a stack trace and so provide some context for what is going on. It may be that whatever is calling Javaassist's FactoryHelper can be changed to obtain the class bytes and use Lookup.defineClass to inject the class (Lookup.defineClass is the supported API for injecting classes into the same runtime package as another class - more discussion on this in https://github.com/jboss-javassist/javassist/issues/145)

**Comment by chibash** [comment]
I've worked on this and committed a fix.  But the solution is transparent for `javassist.util.proxy` but not for `CtClass#toClass()`.  More discussion on this will be in #145.  Please see it.

**Comment by TristeFigure** [comment]
> Wow and she taught you nice manners too.
> [...]
> Close this issue... no body here wants to hear about it.

https://www.buzzfeed.com/mjs538/frightening-truths-about-white-guys-with-dreads

**Comment by xacobecm** [comment]
> Wow and she taught you nice manners too.
> 
> Do you understand what that issue is about?
> Do you even know what this project does? These questions are rhetoric, of course you don't.
> 
> How exactly are you helping? This question you should seriously go think about.
> 
> So everything is working as expected, there's no problems nothing is broken but there's this pesky message instructing you to go tell so and so that even though their stuff works like a charm and didn't cost you a dime they have to stop everything and take note of this.
> 
> No where in between taking instruction from a log message to finding this issue tracker and submitting the ticket did you once stop to think.
> 
> I wonder what this warning is about, should I really go and tell them or do you think they know already?
> Oh and perhaps I should check and see what this project actually does first before I embarrass myself.
> 
> For now focus on helping yourself first only then will you be of any use to others. Look for something to learn from every encounter. Find out what is important to you in this life and choose your battles accordingly. Life is too short to take everything so seriously...
> 
> Close this issue... no body here wants to hear about it.

Africa
