### ISSUE TITLE
ClassPool.makePackage alternative for for Java11 

### ISSUE THREAD

**Issue by vamsi360** [jboss-javassist/javassist#246]
Hi,

We were using classPool.makePackage(currClassLoader, ctClass.getPackageName()) in our code to create a package at runtime.

This is deprecated in Java9+. What is the recommended way of achieving this in Java11? Could you point me to the resources on how to fix this?

**Comment by vamsi360** [comment]
Note: Adding --add-opens java.base/java.lang=ALL-UNNAMED (as described in javadocs) in VM options also doesn't seem to work for me in JDK11

**Comment by NingZhang-Ericsson** [comment]
Seems the java doc in ClassPool is incorrect and needs to be update:
https://github.com/jboss-javassist/javassist/blob/f36195c1451c79b9d46618716cf4efe9904afb32/src/main/javassist/ClassPool.java#L1249
Due to it will not be supported in Java9+:
https://github.com/jboss-javassist/javassist/blob/f36195c1451c79b9d46618716cf4efe9904afb32/src/main/javassist/util/proxy/DefinePackageHelper.java#L50

**Comment by NingZhang-Ericsson** [comment]
One PR to update java doc:
https://github.com/jboss-javassist/javassist/pull/247

**Comment by vamsi360** [comment]
hi @NingZhang-e 
how to makePackage now at runtime going forward? How to migrate existing code? Is there any other way?

**Comment by NingZhang-e** [comment]
I can not figure out a graceful way to go forward. Because define new package conflict with jigsaw policy.
Suggest to abandon make package usage if you want to uplift to Java9+. And make class under one existing package, e.g. org.javassist.
